"""Redis + RQ wiring.

Job lifecycle:
  POST /jobs   → write upload to temp dir, enqueue job (path + filename), return job_id
  RQ worker    → pop job, call extractor.extract(path), result stored in Redis (job.result)
  GET /jobs/id → read job status + result via RQ Job.fetch()

Result TTL = 1h (configurable) — after that, GET /jobs/id returns 404.
"""
from __future__ import annotations

import os
import tempfile
from pathlib import Path

import redis
from rq import Queue
from rq.job import Job

REDIS_URL = os.getenv("REDIS_URL", "redis://localhost:6379/0")
QUEUE_NAME = os.getenv("EXTRACTOR_QUEUE", "extractor")
JOB_TIMEOUT_S = int(os.getenv("JOB_TIMEOUT_S", "600"))  # 10 min — long for big PDFs on cold model
RESULT_TTL_S = int(os.getenv("RESULT_TTL_S", "3600"))   # 1h before result garbage-collected
FAILURE_TTL_S = int(os.getenv("FAILURE_TTL_S", "86400"))  # 24h for failures (debug window)

# Shared upload staging dir — writable by both API and worker containers (volume mount in compose)
UPLOAD_DIR = Path(os.getenv("UPLOAD_DIR", tempfile.gettempdir())) / "extractor-uploads"
UPLOAD_DIR.mkdir(parents=True, exist_ok=True)

_redis: redis.Redis | None = None
_queue: Queue | None = None


def get_redis() -> redis.Redis:
    global _redis
    if _redis is None:
        _redis = redis.from_url(REDIS_URL)
    return _redis


def get_queue() -> Queue:
    global _queue
    if _queue is None:
        _queue = Queue(QUEUE_NAME, connection=get_redis(), default_timeout=JOB_TIMEOUT_S)
    return _queue


def run_extraction(upload_path_str: str, original_filename: str, model: str | None = None) -> dict:
    """Job function executed by RQ worker. Must be top-level importable.

    Returns ExtractionResult.to_dict() — RQ pickles it into job.result. The path-based input
    keeps Redis lean (we don't ship megabytes of PDF through the broker).

    On completion (success OR failure) it fires a fire-and-forget callback to the FE
    (see callback.post_result). The callback never raises, so it can't affect job
    status — the result stays retrievable via GET /jobs/{id} regardless.
    """
    # Import inside function so worker doesn't load Docling at module import time
    # (Docling import is ~3s, loads PyTorch + layout model — defer to first job).
    from datetime import datetime, timezone
    from pathlib import Path as _P
    from rq import get_current_job
    import extractor
    import callback

    upload_path = _P(upload_path_str)
    # RQ injects the running job into this context → gives us the job_id for the payload.
    _job = get_current_job()
    job_id = _job.id if _job is not None else None

    def _completed_payload(status: str, result: dict | None, error: str | None) -> dict:
        return {
            "job_id": job_id,
            "status": status,
            "original_filename": original_filename,
            "result": result,
            "error": error,
            "completed_at": datetime.now(timezone.utc).isoformat(),
        }

    try:
        kwargs = {}
        if model:
            kwargs["model"] = model
        result = extractor.extract(upload_path, **kwargs)
        result_dict = result.to_dict() | {"original_filename": original_filename}
        callback.post_result(_completed_payload("finished", result_dict, None))
        return result_dict
    except Exception as e:
        # Tell the FE the job failed BEFORE re-raising (re-raise marks the RQ job
        # 'failed' so GET /jobs/{id} still surfaces the error to pollers).
        callback.post_result(_completed_payload("failed", None, str(e)))
        raise
    finally:
        # Always clean up staging file — even on exception
        upload_path.unlink(missing_ok=True)


def enqueue_extraction(file_bytes: bytes, filename: str, model: str | None = None) -> Job:
    """API-side helper: persist upload to staging dir, enqueue job."""
    suffix = Path(filename).suffix.lower() or ".bin"
    # Use a UUID-prefixed filename in the staging dir so workers can identify provenance
    import uuid
    upload_path = UPLOAD_DIR / f"{uuid.uuid4().hex}{suffix}"
    upload_path.write_bytes(file_bytes)

    job = get_queue().enqueue(
        run_extraction,
        args=(str(upload_path), filename, model),
        result_ttl=RESULT_TTL_S,
        failure_ttl=FAILURE_TTL_S,
        # job_id auto-generated by RQ if not provided
    )
    return job


def fetch_job(job_id: str) -> Job | None:
    try:
        return Job.fetch(job_id, connection=get_redis())
    except Exception:
        return None
